name: Build and Push Custom Bootc Image

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/silverblue-nic

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf \
            /usr/share/dotnet \
            /usr/local/lib/android \
            /opt/ghc \
            /opt/hostedtoolcache \
            /usr/local/share/powershell \
            /usr/local/share/chromium \
            /var/lib/docker

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reconstruct MOK keys from GitHub Secrets
        run: |
          echo "${{ secrets.MOK_KEY }}" | base64 -d > mok.key
          echo "${{ secrets.MOK_CRT }}" | base64 -d > mok.crt
          echo "${{ secrets.MOK_DER }}" | base64 -d > mok.der

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image with Podman
        run: |
          podman build \
            --target chunkah \
            -v $(pwd):/run/src:rw,z \
            --secret id=mok_key,src=mok.key \
            --secret id=mok_crt,src=mok.crt \
            --secret id=mok_der,src=mok.der \
            . && \
          podman build \
            --target final \
            --format=oci \
            --secret id=mok_key,src=mok.key \
            --secret id=mok_crt,src=mok.crt \
            --secret id=mok_der,src=mok.der \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            .

      - name: Push Image to GHCR
        run: |
          podman push --compression-format zstd ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          podman push --compression-format zstd ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Clean up keys
        if: always()
        run: |
          rm -f mok.key mok.crt mok.der
